### ISSUE TITLE
Incompatibility with quoid/userscripts

### ISSUE THREAD

**Issue by barijaona** [egecelikci/mastodon-bird-ui-userscript#1]
Thanks for this script.

I tried it unsuccessfully with [quoid](https://github.com/quoid) / [userscripts](https://github.com/quoid/userscripts) until I realized that userscripts supports `GM.addStyle`, instead of `GM_addStyle`.

My config :
- macOS Ventura 13.5
- Safari 16.6
- Userscripts 4.4.3 from the Mac App Store

**Comment by barijaona** [comment]
Related : https://github.com/quoid/userscripts/issues/530

**Comment by egecelikci** [comment]
I’ve replaced `GM_addStyle` with `GM.addStyle`, I don't know if this change will make the script work, but as far as I tested with ViolentMonkey, the theme is applied with bugs in the UI. I don’t have a device that I can use to test in Safari.

**Comment by barijaona** [comment]
The UI bugs are probably due do the fact that your instance runs Mastodon 4.1.6, while `main` branch of mastodon-bird-ui is for Mastodon 4.2.0 nightly versions.

Referring to the `stable` branch of mastodon-bird-ui will probably make more sense for the majority of users.
